# Profile
spring:
  profiles:
    active: local
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL5SpatialDialect

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
